### ISSUE TITLE
配置保存不了

### ISSUE THREAD

**Issue by xiaoqiqiab** [fanenr/flutter-chatbot#10]
软件配置好后保存，结束进程后，所有配置被清空，每次都是这样

**Comment by fanenr** [comment]
什么版本？

**Comment by xiaoqiqiab** [comment]
> 什么版本？

最新版，在Download目录创建文件夹正常了

**Comment by fanenr** [comment]
安卓权限导致的，不能随地乱写文件。

**Comment by xiaoqiqiab** [comment]
![Screenshot_2024-11-30-01-21-13-563_cc arthur63 chatbot](https://github.com/user-attachments/assets/a264150c-b5de-4d2b-b5a5-8c0d02d9f441)
发现不是文件夹问题，必须用0.19版本升级到最新版，配置栏目才会显示正常，如果直接安装最新版，配置栏目无法显示，如上图

**Comment by xiaoqiqiab** [comment]
> ![Screenshot_2024-11-30-01-21-13-563_cc arthur63 chatbot](https://private-user-images.githubusercontent.com/50690432/391156353-a264150c-b5de-4d2b-b5a5-8c0d02d9f441.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MDEzODgsIm5iZiI6MTczMjkwMTA4OCwicGF0aCI6Ii81MDY5MDQzMi8zOTExNTYzNTMtYTI2NDE1MGMtYjVkZS00ZDJiLWI1YTUtOGMwZDAyZDlmNDQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDE3MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OWFlYjVlYTg3MTRhNTExYzE3YTA4Yzg3ZmU2NTg3Yzc4MzI5ZTUzNDdjYWZmZjRhMjZjMjVmZDc2MjViMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2Fu8agK_l52IbAjr9hpG10RopfODfDe_VY9QRYIwi9k) 发现不是文件夹问题，必须用0.19版本升级到最新版，配置栏目才会显示正常，如果直接安装最新版，配置栏目无法显示，如上图

在不正常显示的情况下配置保存不了

**Comment by fanenr** [comment]
是 bug，v0.2.4-patch3 修复。

**Comment by xiaoqiqiab** [comment]
每次软件退出后，重新打开之前的对话框，消息展示不能默认显示在最后一条，下拉还是比较麻烦。

**Comment by fanenr** [comment]
> 每次软件退出后，重新打开之前的对话框，消息展示不能默认显示在最后一条，下拉还是比较麻烦。

下个版本更新。

**Comment by xiaoqiqiab** [comment]
> > 每次软件退出后，重新打开之前的对话框，消息展示不能默认显示在最后一条，下拉还是比较麻烦。
> 
> 下个版本更新。

如果能加入字体大小调节，那就完美了，辛苦佬了
