### ISSUE TITLE
公式渲染

### ISSUE THREAD

**Issue by shuimu5418** [fanenr/flutter-chatbot#11]
多行公式使用`\[ \] `的没法渲染啊
![IMG_20241202_110437](https://github.com/user-attachments/assets/06e5275f-61ad-42ba-8992-0d39c287902e)

**Comment by fanenr** [comment]
是上游 md 库的问题，有空再修。

**Comment by fanenr** [comment]
我重写了 LaTeX 解析，可以试试新版本。
