### ISSUE TITLE
多次显示数学公式后报错

### ISSUE THREAD

**Issue by xiaoqiqiab** [fanenr/flutter-chatbot#12]
Parser Error: Undefined control sequence: \cdotp

**Comment by fanenr** [comment]
能详细一点吗？

**Comment by xiaoqiqiab** [comment]
> 能详细一点吗？

ug/(kg ·min) 应该是中间那个点不能显示，\cdotp不能渲染，不是多次显示数学公式的原因，另外之前版本好像能拷贝公式出来，能不能恢复这个功能呀，很方便

**Comment by fanenr** [comment]
是 0.2.7 版本吗，可以的话麻烦提供一下导致解析失败的内容，我查一下。

**Comment by xiaoqiqiab** [comment]
> 是 0.2.7 版本吗，可以的话麻烦提供一下导致解析失败的内容，我查一下。

是0.2.7，
5. **计算药物剂量（µg/(kg·min)）**：
   - 药物剂量 = $\frac{120 \text{ µg/min}}{65 \text{ kg}} \approx 1.846 \text{ µg/(kg·min)}$

综上所述，去甲肾上腺素的剂量为：

$$
\text{去甲肾上腺素剂量} \approx 1.85 \text{ µg/(kg·min)}
$$

### 数据来源
- 药物浓度和输液速率的计算基于药物配制和输液的基本原理。
- 滴液系数的标准值通常为 20 滴/ml，具体可参考临床输液相关文献。
- 以上是显示错误的内容，能不能把拷贝公式加回来，谢谢了佬😚

**Comment by xiaoqiqiab** [comment]
`5. **计算药物剂量（µg/(kg·min)）**：
   - 药物剂量 = $\frac{120 \text{ µg/min}}{65 \text{ kg}} \approx 1.846 \text{ µg/(kg·min)}$

综上所述，去甲肾上腺素的剂量为：

$$
\text{去甲肾上腺素剂量} \approx 1.85 \text{ µg/(kg·min)}
$$

### 数据来源
- 药物浓度和输液速率的计算基于药物配制和输液的基本原理。
- 滴液系数的标准值通常为 20 滴/ml，具体可参考临床输液相关文献。`

**Comment by xiaoqiqiab** [comment]
![Screenshot_2024-12-06-23-18-00-703_cc arthur63 chatbot](https://github.com/user-attachments/assets/1f35fbc4-8580-4a0b-b2a0-19928866eb5a)

**Comment by fanenr** [comment]
好的，我明天研究一下。

**Comment by fanenr** [comment]
Hi，我查了一会。发现是 KaTeX 不支持这种语法（本应用使用 KaTeX 渲染），KaTeX 官网也无法解析：

![image](https://github.com/user-attachments/assets/83696588-9d49-44c3-a2e9-6abe3dab1647)

原因：`\cdot` 和 `·` 都是数学符号（应该在数学模式中使用），在 text 文本块（文本模式）中有转义问题。

**所以，这两个公式是合法的 LaTeX 公式，但不是合法的 KaTeX 公式。**

**建议：在系统提示词中要求模型以 KaTeX 语法输出公式（而不是 LaTeX）。**

**Comment by xiaoqiqiab** [comment]
> Hi，我查了一会。发现是 KaTeX 不支持这种语法（本应用使用 KaTeX 渲染），KaTeX 官网也无法解析：
> 
> ![image](https://private-user-images.githubusercontent.com/63692277/393463807-83696588-9d49-44c3-a2e9-6abe3dab1647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDU2ODAsIm5iZiI6MTczMzU0NTM4MCwicGF0aCI6Ii82MzY5MjI3Ny8zOTM0NjM4MDctODM2OTY1ODgtOWQ0OS00NGMzLWEyZTktNmFiZTNkYWIxNjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA0MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZmE5NjMwOWI4ZDdkMzA5OWRjMTlmZTRhZTNkYzU2MmY3YWIyNzkyYmI5MTZkYTg0ZDBlYTUwM2ZmMzc1MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jPR_samvC8vOlfWiIi9ecAXzBWIVaKysVzt4o8ZeReU)
> 
> 原因：`\cdot` 和 `·` 都是数学符号（应该在数学模式中使用），在 text 文本块（文本模式）中有转义问题。
> 
> **所以，这两个公式是合法的 LaTeX 公式，但不是合法的 KaTeX 公式。**
> 
> **建议：在系统提示词中要求模型以 KaTeX 语法输出公式（而不是 LaTeX）。**

提示语设置的 注意，始终以 Markdown 格式回复，数学公式严格用内嵌 KaTeX 格式输出（用 `$` 包裹行内公式，`$$` 包裹块级公式)。
还是有这个问题

**Comment by fanenr** [comment]
> KaTeX 官网也无法解析

这种情况只能是在模型输出端改进，如果模型太笨也没办法，因为 KaTeX 标准都不支持这种格式，所以严格来说这不是 bug。

**Comment by xiaoqiqiab** [comment]
> > KaTeX 官网也无法解析
> 
> 这种情况只能是在模型输出端改进，如果模型太笨也没办法，因为 KaTeX 标准都不支持这种格式，所以严格来说这不是 bug。

了解了，谢谢大佬解答
