### ISSUE TITLE
希望能出个gemini教程。

### ISSUE THREAD

**Issue by afiooo** [fanenr/flutter-chatbot#17]
感谢支持gemini了，可以发一个简单的教程吗?我在配置的时候各种报错。

**Comment by afiooo** [comment]
主要是api地址不知道到底是哪个。我用了这些:https://gemini.googleapis.com/v1/endpoint
https://generativelanguage.googleapis.com/v1beta/openai/
都没的成功。

**Comment by fanenr** [comment]
以 v1beta 结尾，不带 `/`。

**Comment by afiooo** [comment]
感谢大大，按照您的说明配置成功并自动拉取了模型列表，在聊天的时候又弹出一个错误，不知道是怎么回事？我部署的国内代理地址，地址能打开，模型也能拉成功。出现这个弹窗又是哪里不对？希望大大能帮忙解决。主要是gemini很良心，免费也能用。
![S41210-09252027(1)](https://github.com/user-attachments/assets/7d5ed3ce-0347-49f2-beb5-5ca7ac52c05a)
![S41210-09260692](https://github.com/user-attachments/assets/3eeb307c-2612-4c9a-a524-b331c5d9ecba)

**Comment by fanenr** [comment]
这是网络问题，可以试试挂梯子。

**Comment by afiooo** [comment]
感谢大大。果然挂梯子就能对话了。代理不能用会不会是代理地址被ban了？但是又能成功拉到模型。有点不解。

**Comment by fanenr** [comment]
国内的网络情况一直比较玄学，我也不是很清楚。应用也只是简单地发起网络请求，具体问题可能还是在本机或运营商。

**Comment by oKatTjC** [comment]
我也遇到了相同的问题。
我使用 Deno 反代的 Gemini 链接，在其他项目中([Cherry Studio](https://github.com/kangfenmao/cherry-studio),[chatbot-app](https://github.com/ChatBot-All/chatbot-app))无需翻墙就能正常使用，但在这个 App 里没有翻墙就无法聊天，但模型列表却能够正常同步。

**Comment by fanenr** [comment]
> 我也遇到了相同的问题。
> 我使用 Deno 反代的 Gemini 链接，在其他项目中([Cherry Studio](https://github.com/kangfenmao/cherry-studio),[chatbot-app](https://github.com/ChatBot-All/chatbot-app))无需翻墙就能正常使用，但在这个 App 里没有翻墙就无法聊天，但模型列表却能够正常同步。

是上游 sdk 的问题。
