### ISSUE TITLE
聊天出现了问题

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [fanenr/flutter-chatbot#18]
搭建的[DDG-Chat](https://github.com/leafmoes/DDG-Chat)
每次提问完并回答完后会跳出**type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast**弹窗
![Screenshot_2024-12-12-14-05-29-688_cc arthur63 chatbot-edit](https://github.com/user-attachments/assets/0f2dda94-f2dd-46ed-9232-065a3eec0941)

**Comment by xiaoqiqiab** [comment]
> 搭建的[DDG-Chat](https://github.com/leafmoes/DDG-Chat) 每次提问完并回答完后会跳出**type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast**弹窗 ![Screenshot_2024-12-12-14-05-29-688_cc arthur63 chatbot-edit](https://private-user-images.githubusercontent.com/20140506/395029743-0f2dda94-f2dd-46ed-9232-065a3eec0941.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODQ1MzUsIm5iZiI6MTczMzk4NDIzNSwicGF0aCI6Ii8yMDE0MDUwNi8zOTUwMjk3NDMtMGYyZGRhOTQtZjJkZC00NmVkLTkyMzItMDY1YTNlZWMwOTQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA2MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OGI3OTU2ZWZmNjVhY2JjMDgwM2RjY2U5MDJmYmQyNTU0YWQ4ODRkY2RkNjdjYjEwMjdjZDNlYTkyZWEwMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mD8_oh_Nfn4NeGs2IAAWcQvyKfYAqekagr3sQHVF9BU)

这个问题我也提交了，我还发现个问题，用这个提问会大部分时间回答是gpt3模型，用chatbox不会有这个问题
![Screenshot_2024-12-12-14-21-24-958_cc arthur63 chatbot](https://github.com/user-attachments/assets/df6bbc55-0cdc-4722-9ac0-3c0da517b64d)
![Screenshot_2024-12-12-14-21-44-133_xyz chatboxapp chatbox](https://github.com/user-attachments/assets/69186749-7046-4a96-b652-ea1103f6ed30)

**Comment by bestZwei** [comment]
遇到一样的问题

**Comment by fanenr** [comment]
错误发生在上游的 openai sdk，但我估计是这个 ddg 的响应不规范。

**Comment by fanenr** [comment]
> 这个问题我也提交了，我还发现个问题，用这个提问会大部分时间回答是gpt3模型，用chatbox不会有这个问题 !

即使用 openai 的官方 api 问这个问题，gpt-4o-mini 乃至 gpt-4o 都有概率说它自己是 GPT-3。这个与预设提示词有关（gpt 模型并不知道它自己是什么版本）。

**Comment by keung67** [comment]
@fanenr new-api中轉azure gpt-4o，聊天流式完成同樣跳出type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
識圖的聊天斷流，未回答完就跳此錯誤，希望能修復。其他客戶端都正常。
