### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by bestZwei** [fanenr/flutter-chatbot#20]
![Screenshot_2024-12-13-10-16-17-010_cc arthur63 chatbot-edit](https://github.com/user-attachments/assets/d33a32ab-9418-4b0b-b1bd-4622681f2ca2)
希望己方发送的消息也有这一选项。

另外，我发现一个问题，对话输出的过程中，对话区一直向下滚动，无法停止

**Comment by fanenr** [comment]
只给最后一条消息加小按钮是因为手机屏幕空间有限，每条消息下面都加的话会占用很多空间，而且不美观。设计的交互逻辑就是响应时列表自动滚动，这样方便查看。
