### ISSUE TITLE
请求支持groq

### ISSUE THREAD

**Issue by sprindjack** [fanenr/flutter-chatbot#21]
现在使用groq会报错，弹框如下
OpenAIClientException({
  "uri": "https://api.groq.com/openai/v1/chat/completions",
  "method": "POST",
  "code": 400,
  "message": "Unsuccessful response",
  "body": {
    "error": {
      "message": "property 'store' is unsupported, did you mean 'stop'?",
      "type": "invalid_request_error"
    }
  }
})

**Comment by fanenr** [comment]
现在似乎可以了。
