### ISSUE TITLE
请教下这个只支持xai吗？

### ISSUE THREAD

**Issue by afiooo** [fanenr/flutter-chatbot#8]
其它的比如groq  gemini openai等其它AI支持吗？

**Comment by fanenr** [comment]
目前只支持 OpenAI 格式接口。

**Comment by afiooo** [comment]
> 目前只支持 OpenAI 格式接口。

感谢大神的这个项目，使用起来简洁明快，打开飞快。我现在能使用xai  openai.就是groq的用不了，这个是兼容openai的，xai也是兼容openai可用。groq问问题出现:OpenAIClientException({
  "uri": "https://groq.******.***/openai/v1/chat/completions",
  "method": "POST",
  "code": 400,
  "message": "Unsuccessful response",
  "body": {
    "error": {
      "message": "property 'store' is unsupported, did you mean 'stop'?",
      "type": "invalid_request_error"
    }
  }
})
配置没有问题，可以成功拉取模型。想请大神给解惑，如果是目前还不支持希望能加上，等gemini加上对我来说就完美了。非常感谢！

**Comment by fanenr** [comment]
这个是上游 openai sdk 的问题，它会附加一个 store 参数，但是 azure 和 groq 都不支持这个参数，最近会试着修复一下。本来想兼容 gemini 格式的，但是最近 gemini 好像官方兼容 openai 格式了，不知道能直接用不，能用的话也可以省点事。

**Comment by yyyzl** [comment]
Gemini的也会报上方的store错误，期待大佬修复
